### ISSUE TITLE
port to godot3 

### ISSUE THREAD

**Issue by blurymind** [marcosbitetti/grass_plugin_4_godot#5]
please ? :)

**Comment by Akira1San** [comment]
We need this for Godot 3!

**Comment by DigitalMonkeyPa1** [comment]
I am working on that.....

**Comment by marcosbitetti** [comment]
Current work project to 3.1 is on working, using gdnative

**Comment by zhagsenkk** [comment]
thx

**Comment by marcosbitetti** [comment]
Started :+1: 

[https://godotdevelopers.org/forum/discussion/comment/24463/#Comment_24463](url)
